# Basic
title: Yeer Fan
subtitle:  Code, Design, and Things in Between 
welcome_message: <a href="" target="_blank">Just Help Yourself</a>
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
# description: Vno Jekyll is a port of my Ghost theme vno.
# creator: <a href="http://onev.cat">@onevcat</a>

repository: fanyer/fanyer.github.io


url: "http://blog.capcat.top/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: sysu_fanyer
    github: fanyer
    twitter: fanyer
    mail: iofanyer@live.com
    # gplus: 107108267983477358170
    # mail: fanyer@capcat.top

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
